### ISSUE TITLE
バグ) 一覧表示・場所

### ISSUE THREAD

**Issue by ZOMMMMMMMMM** [manmen-mi/ziqsche#26]
**バグ概要**
スケジュール一覧表示画面で場所カラムの内容が表示されてない

**再現方法**

　1.localhost:8080/scheに接続
　2.ID:'tester', password:'tester'でログイン
　3.一覧表示ボタンをクリック
　4.事象確認

**想定値**
カレンダー一覧表示の時、すべてのスケジュール情報が表示される

**エビデンス**
バグの箇所がわかるような画像ファイルがあれば、残してください。
![20181225](https://user-images.githubusercontent.com/45378073/50414740-8b614f80-085a-11e9-98ac-fa8d0972b00e.jpg)

**Comment by ZOMMMMMMMMM** [comment]
原因：スケジュール情報を取得する際、場所情報の取得漏れ
対応：DbConnectionManagerクラスのgetScheduleListを修正

**Comment by manmen-mi** [comment]
レビュー＆マージしました。
